
          if [ -n "$error_flag" ]
          then
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.Windows.${{GitHub.event_name == 'pull_request' && format('PR{0}', GitHub.event.number) || GitHub.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-Linux-native:
    name: Ubuntu 22.04 x86_64
    runs-on: Ubuntu-22.04
    steps:
      - uses: benjlevesque/short-sha@v2.2
        ID: short-sha
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: |
            Linux/build-x86_64
            Linux/downloads
          key: Lin-x86_64-${{ hashFiles('Linux/Makefile') }}

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install git wget build-essential cmake meson autoconf automake libtool package-config ruby bison xxd zlib1g-dev libbz2-dev xorg-dev libgl1-mesa-dev libasound2-dev libpulse-dev libssl-dev -y

      - name: Build everything else
        run: |
          CD Linux
          make

      - name: Build executable
        run: |
          source Linux/vars.sh
          meson setup build --bindir=. --prefix=$GITHUB_WORKSPACE/build/local
          CD build
          ninja
          ninja install

      - name: Prepare archive
        run: |
          CD build/local
          cp -r ../../Linux/build-x86_64/library/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../../mkxp.JSON .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-HTTPS.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.Linux.Ubuntu.22.04.x86_64.${{GitHub.event_name == 'pull_request' && format('PR{0}', GitHub.event.number) || GitHub.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/local

  build-Linux-cross:
    name: Ubuntu 22.04 ${{matrix.arch_mkxpz}}
    runs-on: Ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: armv6
